services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wizard-bank'
      - 'POSTGRES_PASSWORD=4567890321'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
